import { Inter } from "next/font/google";
import "../globals.css";
import ReduxProviders from "@components/ReduxProvier";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Authentication",
  description: "Generated by Authentication",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProviders>
          {children}
        </ReduxProviders>
      </body>
    </html>
  );
}
